
spring.flyway.enabled: false

app:
  foo: bar
  initialize-dummy-data: true

spring:
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  devtools.remote.secret: secret

minio:
  access-key: minioadmin
  access-secret: minioadmin
  bucket-name: foo
  endpoint: http://127.0.0.1:9000

server:
  port: 8012