POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "username": "user@domain.com",
  "password": "password"
}

###

POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "username": "user@domain.com",
  "password": "password"
}

###

GET http://localhost:8080/api/sample/admin
Content-Type: application/json
Authorization: Bearer

###

GET http://localhost:8080/api/sample/user
Content-Type: application/json
Authorization: Bearer

###

POST http://localhost:8080/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "",
  "token": ""
}