POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "username": "user@domain.com",
  "password": "password"
}

###

POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "username": "user@domain.com",
  "password": "password"
}

###

GET http://localhost:8080/api/sample
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQGRvbWFpbi5jb20iLCJpYXQiOjE2MjAxMTI0NjIsImV4cCI6MTYyMDExNDI2Mn0.8269xNrJ00LTVCuVe7cXiWAsF5LZNrEj2qyIdgiBzfwzaiBLJWPTo2bpc-Mca6RIygo8YGmQDRMWo0c8Au87tQ

###

POST http://localhost:8080/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "ec7baac2-d092-4302-8abc-bfbe09fed79c",
  "token": "eyJhbGci1iJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQGRvbWFpbi5jb20iLCJpYXQiOjE2MjAxMTI0NjIsImV4cCI6MTYyMDExNDI2Mn0.8269xNrJ00LTVCuVe7cXiWAsF5LZNrEj2qyIdgiBzfwzaiBLJWPTo2bpc-Mca6RIygo8YGmQDRMWo0c8Au87tQ"
}